import configparser

from fpvdgs.render import render_cfg, write_cfg

EFFECTIVE = {
    "link": {"channel": 132, "width": 40, "txpower": 19, "region": "US",
             "linkId": 7669206, "beamforming": {"enabled": False}, "wlans": "auto"},
    "wfb": {"profile": "gs", "mavlink": {"peer": "connect://127.0.0.1:14550"},
            "raw": {"gs_tunnel": {"ldpc": "1"}}},
    "drone": {"endpoint": "http://10.5.0.10:8080"},
}


def _parse(text):
    cp = configparser.RawConfigParser(strict=False)
    cp.read_string(text)
    return cp


def test_render_has_generated_header():
    text = render_cfg(EFFECTIVE)
    assert text.lstrip().startswith("#")
    assert "generated by fpvd" in text.lower()


def test_render_maps_common_section():
    cp = _parse(render_cfg(EFFECTIVE))
    assert cp.get("common", "wifi_channel") == "132"
    assert cp.get("common", "wifi_region") == "'US'"
    assert cp.get("common", "wifi_txpower") == "19"


def test_render_maps_video_bandwidth_from_width():
    cp = _parse(render_cfg(EFFECTIVE))
    assert cp.get("gs_video", "bandwidth") == "40"


def test_render_maps_mavlink_peer():
    cp = _parse(render_cfg(EFFECTIVE))
    assert cp.get("gs_mavlink", "peer") == "connect://127.0.0.1:14550"


def test_render_raw_passthrough():
    cp = _parse(render_cfg(EFFECTIVE))
    assert cp.get("gs_tunnel", "ldpc") == "1"


def test_write_cfg_atomic_keeps_bak(tmp_path):
    p = tmp_path / "wifibroadcast.cfg"
    write_cfg(str(p), "first\n")
    write_cfg(str(p), "second\n")
    assert p.read_text() == "second\n"
    assert (tmp_path / "wifibroadcast.cfg.bak").read_text() == "first\n"
