import ast
import configparser

from fpvdgs.render import render_cfg, write_cfg

EFFECTIVE = {
    "link": {
        "channel": 132,
        "width": 40,
        "txPowerDbm": 19,
        "region": "US",
        "linkId": 7669206,
        "beamforming": {"enabled": False},
        "wlans": "auto",
    },
    "wfb": {
        "profile": "gs",
        "mavlink": {"peer": "connect://127.0.0.1:14550"},
        "raw": {"gs_tunnel": {"ldpc": 1}},
    },
    "drone": {"endpoint": "http://10.5.0.10:8080"},
}


def _parse_literals(text):
    """Parse the way wfb-ng does: ast.literal_eval every value. Raises if any
    value is not a valid Python literal (e.g. an unquoted URL)."""
    cp = configparser.RawConfigParser(strict=False)
    cp.read_string(text)
    out = {}
    for section in cp.sections():
        out[section] = {k: ast.literal_eval(v) for k, v in cp.items(section)}
    return out


def test_render_has_generated_header():
    text = render_cfg(EFFECTIVE)
    assert text.lstrip().startswith("#")
    assert "generated by fpvd" in text.lower()


def test_every_value_is_a_valid_python_literal():
    # wfb-ng runs ast.literal_eval on each cfg value; a non-literal (e.g. an
    # unquoted peer URL) makes the daemon fail to start. This guards that class.
    _parse_literals(render_cfg(EFFECTIVE))


def test_render_maps_common_section():
    cfg = _parse_literals(render_cfg(EFFECTIVE))
    assert cfg["common"]["wifi_channel"] == 132
    assert cfg["common"]["wifi_region"] == "US"
    assert cfg["common"]["wifi_txpower"] == 1900


def test_render_omits_txpower_when_unset():
    eff = {"link": {"channel": 132, "width": 40, "region": "US"}, "wfb": {}}
    cfg = _parse_literals(render_cfg(eff))
    assert "wifi_txpower" not in cfg["common"]


def test_render_does_not_emit_link_id():
    # link_id is derived from link_domain in wfb-ng; there is no link_id key.
    cfg = _parse_literals(render_cfg(EFFECTIVE))
    assert "link_id" not in cfg["common"]


def test_render_maps_video_bandwidth_from_width():
    cfg = _parse_literals(render_cfg(EFFECTIVE))  # width 40
    assert cfg["gs_video"]["bandwidth"] == 40
    # uplink services cap at 20 MHz (the card width comes from gs_video=40)
    assert cfg["gs_mavlink"]["bandwidth"] == 20
    assert cfg["gs_tunnel"]["bandwidth"] == 20


def test_render_10mhz_narrows_all_services():
    # The card width = max(all service bandwidths), so a 10 MHz link must narrow
    # every service to 10 or the card stays at 20.
    eff = {
        "link": {"channel": 132, "width": 10, "region": "US"},
        "wfb": {"mavlink": {"peer": "connect://127.0.0.1:14550"}},
    }
    cfg = _parse_literals(render_cfg(eff))
    assert cfg["gs_video"]["bandwidth"] == 10
    assert cfg["gs_mavlink"]["bandwidth"] == 10
    assert cfg["gs_tunnel"]["bandwidth"] == 10


def test_render_maps_mavlink_peer():
    cfg = _parse_literals(render_cfg(EFFECTIVE))
    assert cfg["gs_mavlink"]["peer"] == "connect://127.0.0.1:14550"


def test_render_raw_passthrough():
    cfg = _parse_literals(render_cfg(EFFECTIVE))
    assert cfg["gs_tunnel"]["ldpc"] == 1


def test_write_cfg_atomic_keeps_bak(tmp_path):
    p = tmp_path / "wifibroadcast.cfg"
    write_cfg(str(p), "first\n")
    write_cfg(str(p), "second\n")
    assert p.read_text() == "second\n"
    assert (tmp_path / "wifibroadcast.cfg.bak").read_text() == "first\n"


def test_render_emits_10hz_log_interval():
    from fpvdgs import render

    cfg = {"link": {"channel": 132, "width": 40, "region": "US"}, "wfb": {}}
    text = render.render_cfg(cfg)
    assert "log_interval = 100" in text
    # it belongs to [common]
    common = text.split("[common]", 1)[1].split("[", 1)[0]
    assert "log_interval = 100" in common
