"""Render the effective config to /etc/wifibroadcast.cfg (a generated artifact)."""

import os

HEADER = (
    "# generated by fpvd — do not edit.\n"
    "# source of truth: /etc/fpvd/{defaults,config}.json\n"
)


def render_cfg(effective: dict) -> str:
    link = effective.get("link", {})
    wfb = effective.get("wfb", {})
    lines = [HEADER, "[common]"]
    lines.append(f"wifi_channel = {link['channel']}")
    lines.append(f"wifi_region = '{link['region']}'")
    if link.get("txpower") is not None:
        lines.append(f"wifi_txpower = {link['txpower']}")
    if link.get("linkId") is not None:
        lines.append(f"link_id = {link['linkId']}")

    # gs_video: width drives the card bandwidth (HT20/HT40)
    lines.append("")
    lines.append("[gs_video]")
    lines.append(f"bandwidth = {link['width']}")

    mav = wfb.get("mavlink", {})
    if mav.get("peer"):
        lines.append("")
        lines.append("[gs_mavlink]")
        lines.append(f"peer = {mav['peer']}")

    # raw passthrough: {section: {key: value}}
    for section, kv in (wfb.get("raw") or {}).items():
        lines.append("")
        lines.append(f"[{section}]")
        for key, value in kv.items():
            lines.append(f"{key} = {value}")

    return "\n".join(lines) + "\n"


def write_cfg(path: str, text: str) -> None:
    """Atomic write; previous content preserved as <path>.bak."""
    if os.path.exists(path):
        os.replace(path, path + ".bak")
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, path)
