#!/bin/sh
DAEMON=fpvd
DAEMON_PATH=/usr/bin/fpvd
PIDFILE=/var/run/fpvd.pid
LOG=/tmp/fpvd.log
DAEMON_ARGS="--log $LOG"

start() {
    printf 'Starting %s: ' "$DAEMON"
    start-stop-daemon -S -q -b -m -p "$PIDFILE" -x "$DAEMON_PATH" -- $DAEMON_ARGS
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf 'Stopping %s: ' "$DAEMON"
    start-stop-daemon -K -q -p "$PIDFILE"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)   start ;;
    stop)    stop ;;
    restart) stop; sleep 1; start ;;
    *) echo "Usage: $0 {start|stop|restart}"; exit 1 ;;
esac
